# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a56466e1f53d70cedc6f9a764071ec4324473d1fcedb54622cae4345d5b5b29f8773c9b6199906214fc77af0485ba09ea44cf503cf36345870a722178878540e

test:
  secret_key_base: da008608097d39cf9acdf1757e952c441ac1a3f027a9561e0e89fc2cc75afc8101b3279e2d861edd19f024650742958ec7ba6017b834dae51fc5c3517d1396bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
